// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
"use strict";

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Js_option from "bs-platform/lib/es6/js_option.js";
import * as Format from "date-fns/format";

const flip = (f, a, b) => {
  return Curry._2(f, b, a);
};

const format = (param, param$1) => {
  return Format(param$1, param);
};

const result = format("DD/MM/YYYY", new Date("2018-02-25T07:18:40.942Z"));
export { result };
/* date-fns/parse Not a pure module */
