// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

import * as DateFns from "./DateFns.js";

var result = DateFns.format("DD/MM/YYY", new Date("2018-02-25T07:18:40.942Z"));

export {
  result ,
  
}
/* result Not a pure module */
